variables:
  ###
  # IMPORTANT
  # These are the version tags for the docker images the CI runs against.
  # If you are hacking on them or need a them to rebuild, its enough
  # to change any part of the string of the image you want.
  ###
  FEDORA_TAG:  '2026-02-26.0'

  DEBIAN_TAG:  '2026-02-26.0'

  CHECKS_TAG: '2026-01-27.0'

  ABI_CHECK_TAG: '2026-02-19.0'

  WINDOWS_TAG: '2026-02-26.0'
