#undef PACKAGE
#undef VERSION

/* Gettext stuff */
#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY

#undef PLUGINS_DIR
#undef PLUGINS_SRCDIR
#undef PLUGINS_USE_SRCDIR

#undef GST_CONFIG_DIR
#undef GST_WIN32_LIBDIR

#undef HAVE_CPU_I386
#undef HAVE_CPU_PPC
#undef HAVE_CPU_ALPHA
#undef HAVE_CPU_ARM
#undef HAVE_CPU_SPARC

#undef HAVE_RDTSC

#undef HAVE_GDK_PIXBUF
#undef HAVE_LIBGHTTP
#undef HAVE_LIBMMX
#undef HAVE_LIBXV
#undef HAVE_LIBAUDIOFILE
#undef HAVE_OSS
#undef HAVE_XAUDIO
#undef HAVE_CSSAUTH
#undef HAVE_VORBIS
#undef HAVE_LIBMAD
#undef HAVE_LIBJPEG
#undef HAVE_LIBSDL
#undef HAVE_LIBHERMES
#undef HAVE_NASM
#undef HAVE_MPEG2DEC
#undef HAVE_LINUX_CDROM
#undef HAVE_LINUX_VIDEODEV
#undef HAVE_LIBSDL
#undef HAVE_LIBOPENQUICKTIME

#undef HAVE_ATOMIC_H

#undef GST_DEBUG_ENABLED
#undef GST_INFO_ENABLED
#undef GST_INFO_ENABLED_VERBOSE
#undef GST_INFO_FORCE_DISABLE
#undef GST_DEBUG_COLOR
