#undef PLUGINS_DIR
#undef PLUGINS_SRCDIR
#undef PLUGINS_USE_SRCDIR

#undef GST_CONFIG_DIR

#undef HAVE_CPU_I386
#undef HAVE_CPU_PPC

#undef HAVE_GDK_PIXBUF
#undef HAVE_LIBGHTTP
#undef HAVE_LIBMMX
#undef HAVE_LIBXV
#undef HAVE_XAUDIO
#undef HAVE_CSSAUTH
#undef HAVE_VORBIS
#undef HAVE_LIBJPEG
#undef HAVE_NASM

#undef HAVE_ATOMIC_H

#undef GST_DEBUG_ENABLED
#undef GST_INFO_ENABLED
#undef GST_INFO_ENABLED_VERBOSE
#undef GST_INFO_FORCE_DISABLE
