#!/bin/sh

Template=$1;
srcfile=$2;

if test x"$1" = x ; then
	echo "$0 Objectname [srcfile]\n";
	echo "  creates gstobjectname.{c,h} implementing GstObjectname,\n";
	echo "  subclassing GstVideofilter.\n";
	exit 1;
fi

if test x"$2" = x ; then
	srcfile="gstvideotemplate.c"
fi

id=$(echo '$Id$I[d]: \(.*\)\$/\1/g" )

TEMPLATE=$(echo $Template | tr a-z A-Z)
template=$(echo $Template | tr A-Z a-z)

# remember to break up the Id: in the line below
sed \
	-e "s/gstvideotemplate\.c/SOURCEFILE/g" \
	-e "s/Videotemplate/$Template/g" \
	-e "s/videotemplate/$template/g" \
	-e "s/VIDEOTEMPLATE/$TEMPLATE/g" \
	-e "s/\$I[d]: \(.*\)\$/\1/g" \
	-e "s/SOURCEFILE/gstvideotemplate\.c/g" \
	-e "s/MAKEFILTERVERSION/$id/g" \
	$srcfile >gst$template.c

