
/* autogenerated from gstaudioconvertorc.orc */

#ifndef _GSTAUDIOCONVERTORC_H_
#define _GSTAUDIOCONVERTORC_H_

#include <glib.h>

#ifdef __cplusplus
extern "C" {
#endif

void orc_audio_convert_unpack_u8 (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_s8 (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_u16 (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_s16 (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_u16_swap (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_s16_swap (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_u32 (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_s32 (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_u32_swap (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_unpack_s32_swap (gint32 * d1, const guint8 * s1, int p1, int n);
void orc_audio_convert_pack_u8 (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_s8 (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_u16 (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_s16 (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_u16_swap (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_s16_swap (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_u32 (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_s32 (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_u32_swap (guint8 * d1, const gint32 * s1, int p1, int n);
void orc_audio_convert_pack_s32_swap (guint8 * d1, const gint32 * s1, int p1, int n);

#ifdef __cplusplus
}
#endif

#endif

