#!/bin/sh

if [ $# -ge 1 ]; then
  DEVICE_OPT="device=$1"
else
  DEVICE_OPT=""
fi

gst-launch rsndvdbin name=dvd "$DEVICE_OPT" \
   dvdspu name=spu ! videoconvert ! videoscale ! ximagesink force-aspect-ratio=true \
   dvd. ! queue max-size-buffers=3 max-size-bytes=0 ! spu.video \
   dvd. ! spu.subpicture \
   dvd. ! audioconvert ! autoaudiosink
