FROM registry.freedesktop.org/gstreamer/gst-ci/amd64/ubuntu-runtime

# make source packages available in order to figure out build dependencies
RUN  \
    sed -i "s/# deb-src/deb-src/g" /etc/apt/sources.list && \
    apt-get update && \
    apt-get -y build-dep \
    orc \
    gstreamer1.0 \
    gst-plugins-base1.0 \
    gst-plugins-good1.0 \
    gst-plugins-bad1.0 \
    gst-plugins-ugly1.0 \
    gst-libav1.0 \
    gst-rtsp-server1.0 \
    gst-python1.0 \
    gstreamer-vaapi \
    gstreamer-editing-services1.0 && \
    apt-get -y install \
    ccache \
    gdb \
    git \
    xvfb \
    python3-pip \
    wget

RUN pip3 install meson

ENV GST_BUILD_PATH="/gst-build/"

# Configure git for various usage
RUN git config --global user.email "gst-build@gstreamer.net" && git config --global user.name "Gstbuild Runner"

# get gst-build and make all subprojects available
RUN git clone git://anongit.freedesktop.org/gstreamer/gst-build $GST_BUILD_PATH && \
    cd $GST_BUILD_PATH && \
    meson build/ && rm -rf build/