FROM registry.freedesktop.org/gstreamer/gst-ci/amd64/fedora-runtime
# Add rpmfusion repositories and install all build dependencies of GStreamer
RUN dnf builddep -y \
        gstreamer1 \
        gstreamer1-plugins-base \
        gstreamer1-plugins-good \
        gstreamer1-plugins-good-extras \
        gstreamer1-plugins-ugly \
        gstreamer1-plugins-ugly-free \
        gstreamer1-plugins-bad-nonfree \
        gstreamer1-plugins-bad-free \
        gstreamer1-plugins-bad-free-extras \
        gstreamer1-plugins-bad-freeworld \
        gstreamer1-libav \
        gstreamer1-rtsp-server  \
        gstreamer1-vaapi \
        python3-gstreamer1 \
    && \
    rpm -e \
        gstreamer1-devel \
        gstreamer1-plugins-base-devel \
        gstreamer1-plugins-bad-free-devel \
    && \
    dnf install -y \
        ccache \
        gcc \
        gcc-c++ \
        gdb \
        git \
        ffmpeg \
        ffmpeg-libs \
        ffmpeg-devel \
        procps-ng \
        patch \
        redhat-rpm-config \
        json-glib \
        json-glib-devel \
        libnice \
        libnice-devel \
        libunwind \
        libunwind-devel \
        opencv \
        opencv-devel \
        openjpeg2 \
        openjpeg2-devel \
        x264 \
        x264-libs \
        x264-devel \
        pygobject3-devel \
        python3-gobject \
        python3-cairo \
        python3-cairo-devel \
        xorg-x11-server-utils \
        xorg-x11-server-Xvfb \
        ninja-build && \
        cmake && \
        rsync && \
    dnf clean all && \
    pip3 install meson hotdoc && \
    export PATH="$PATH:/usr/local/lib/python3.6/site-packages"

ENV GST_BUILD_PATH="/gst-build/"

# Configure git for various usage
RUN git config --global user.email "gst-build@gstreamer.net" && git config --global user.name "Gstbuild Runner"

# get gst-build and make all subprojects available
RUN git clone git://anongit.freedesktop.org/gstreamer/gst-build $GST_BUILD_PATH && \
    cd $GST_BUILD_PATH && \
    meson build/ && \
    rm -rf build/
