FROM registry.freedesktop.org/thiblahute/gst-ci/amd64/fedora-runtime

# Add rpmfusion repositories and install all build dependencies of GStreamer
RUN dnf builddep -y \
       gstreamer1 \
       gstreamer1-plugins-base \
       gstreamer1-plugins-good \
       gstreamer1-plugins-good-extras \
       gstreamer1-plugins-ugly \
       gstreamer1-plugins-ugly-free \
       gstreamer1-plugins-bad-nonfree \
       gstreamer1-plugins-bad-free \
       gstreamer1-plugins-bad-free-extras \
       gstreamer1-plugins-bad-freeworld \
       gstreamer1-libav \
       gstreamer1-rtsp-server  \
       python3-gstreamer1 \
    && \
    rpm -e \
       gstreamer1-devel \
       gstreamer1-plugins-base-devel \
    && \
    dnf install -y \
    	ccache \
	gcc-c++ \
	gdb \
	git \
	json-glib-devel \
	libunwind-devel \
	opencv-devel \
	openjpeg2-devel \
	patch \
	redhat-rpm-config \
	xorg-x11-server-Xvfb \
	xorg-x11-server-utils \
	ninja-build \
    wget && \
    dnf clean all

RUN pip3 install meson

ENV GST_BUILD_PATH="/gst-build/"
ENV GST_VALIDATE_OUTPUT="/validate-output"
ENV GST_VALIDATE_TESTSUITES="$GST_VALIDATE_OUTPUT/gst-integration-testsuites"
# FIXME Enabled gst-libav.
ENV GST_BUILD_MESON_ARGS="-Dpython=disabled -Dlibav=disabled -Dugly=enabled -Dbad=enabled -Ddevtools=enabled -Dges=enabled -Drtsp_server=enabled -Domx=disabled -Dvaapi=disabled -Dsharp=disabled"

# Configure git for various usage
RUN git config --global user.email "gst-build@gstreamer.net" && git config --global user.name "Gstbuild Runner"

# get gst-build and make all subprojects available
RUN git clone git://anongit.freedesktop.org/gstreamer/gst-build $GST_BUILD_PATH && \
    cd $GST_BUILD_PATH && \
    meson build/ $GST_BUILD_MESON_ARGS