For now use:

  db2html gstreamer-manual 

You will need the png support for docbook (see GNOME documentation project)

convert the fig images to png with:

  fig2dev -L png -s 16 fig/<input file>.fig images/<input file>.png

Put a link in the gstreamer-manual directory with

  ln -s ../images gstreamer-manual/images

point your browser to gstreamer-manual/gstreamer.html

Fix typing errors and correct bad english.
Let me know about the stuff that needs some more explanation.
Let me know about the structure of the document.
