.TH GES\-LAUNCH\-1.0 "1" "December 2016" "GStreamer Editing Services API version 1.0" "User Commands"
.SH NAME
ges\-launch\-1.0 \- create and render multimedia timelines
.SH "SYNOPSIS"
\fBges\-launch\-1.0\fR \fI[OPTION...]\fR
.SH DESCRIPTION
ges\-launch\-1.0 creates a multimedia timeline and plays it back,
or renders it to the specified format.
.PP
It can load a timeline from an existing project, or create one
from the specified commands.
.PP
You can learn more about individual ges\-launch\-1.0 commands with
"ges\-launch\-1.0 help command".
.PP
By default, ges\-launch\-1.0 is in "playback\-mode".
.SH "OPTIONS"
For the full list of \fIges\-launch\-1.0\fP options see the command line help:
.TP 8
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP 8
\fB\-\-help\-all\fR
Show all help options
.TP 8
\fB\-\-help\-gst\fR
Show GStreamer Options
.TP 8
\fB\-\-help\-GES\fR
Show GES Options
.TP 8
\fB\-\-help\-project\fR
Show project\-related options
.TP 8
\fB\-\-help\-rendering\fR
Show rendering options
.TP 8
\fB\-\-help\-playback\fR
Show playback options
.TP 8
\fB\-\-help\-informative\fR
Show informative options
.SH "SEE ALSO"
For more detailed info and some examples of use, also check out the on-line documentation:
.br
https://gstreamer.freedesktop.org/documentation/tools/ges-launch.html
.SH "AUTHOR"
Antonio Ospite https://ao2.it
