#!/usr/bin/env python3

import urllib.request
import shutil
import sys
import os

os.makedirs(os.path.dirname(sys.argv[2]), exist_ok=True)

with urllib.request.urlopen(sys.argv[1]) as response, open(sys.argv[2], 'wb') as out_file:
    shutil.copyfileobj(response, out_file)
