/* values match GstVideoMultiviewMode */
#define VIEW_MONO_DOWNMIX 0
#define VIEW_MONO_LEFT 1
#define VIEW_MONO_RIGHT 2
#define VIEW_SIDE_BY_SIDE 3
/*  GST_VIDEO_MULTIVIEW_MODE_SIDE_BY_SIDE_QUINCUNX,*/
#define VIEW_COLUMN_INTERLEAVED 5
#define VIEW_ROW_INTERLEAVED 6
#define VIEW_TOP_BOTTOM 7
#define VIEW_CHECKERBOARD 8
