// This file was generated by the Gtk# code generator.
// Changed to include the BalanceType property

namespace Gst.Interfaces {

	using System;

#region Autogenerated code
	public interface ColorBalance : GLib.IWrapper {
		Gst.Interfaces.ColorBalanceType BalanceType {
			get ;
		}

		event Gst.Interfaces.ValueChangedHandler ValueChanged;
		void SetValue(Gst.Interfaces.ColorBalanceChannel channel, int value);
		Gst.Interfaces.ColorBalanceChannel[] ListChannels();
		int GetValue(Gst.Interfaces.ColorBalanceChannel channel);
		void EmitValueChanged(Gst.Interfaces.ColorBalanceChannel channel, int value);
	}

	[GLib.GInterface (typeof (ColorBalanceAdapter))]
	public interface ColorBalanceImplementor : GLib.IWrapper {

		Gst.Interfaces.ColorBalanceChannel[] ListChannels ();
		void SetValue (Gst.Interfaces.ColorBalanceChannel channel, int value);
		int GetValue (Gst.Interfaces.ColorBalanceChannel channel);
	}
#endregion
}
