// This file was generated by the Gtk# code generator.
// Changed to take strings instead of GParamSpecs.

namespace Gst.Interfaces {

	using System;

	public partial interface PropertyProbe : Gst.GLib.IWrapper {
		event Gst.Interfaces.ProbeNeededHandler ProbeNeeded;

		string[] Properties { get; }
		object[] GetValues (string property);
		bool NeedsProbe (string property);
		void Probe (string property);

		object[] ProbeAndGetValues (string property);
	}

	[Gst.GLib.GInterface (typeof (PropertyProbeAdapter))]
	public partial interface PropertyProbeImplementor : Gst.GLib.IWrapper {
		string[] Properties { get; }
		bool NeedsProbe (string property);
		void ProbeProperty (string property);
		object[] GetValues (string property);
	}
}
