
/* autogenerated from gstvideoboxorc.orc */

#ifndef _GSTVIDEOBOXORC_H_
#define _GSTVIDEOBOXORC_H_

#include <glib.h>

#ifdef __cplusplus
extern "C" {
#endif

void orc_splat_u32 (guint32 * d1, int p1, int n);

#ifdef __cplusplus
}
#endif

#endif

