FROM fedora:29

# System setup
RUN echo "fastestmirror=true" >>  /etc/dnf/dnf.conf && \
    dnf upgrade -y && \
    dnf install -y sudo git rsync

# Configure git for various usage
RUN git config --global user.email "cerbero@gstreamer.freedesktop.org" && \
    git config --global user.name  "Cerbero Build System"

RUN git clone https://gitlab.freedesktop.org/gstreamer/cerbero.git && \
    mkdir $HOME/.cerbero && \
    echo "allow_parallel_build=True" > $HOME/.cerbero/cerbero.cbc && \
    echo "use_ccache=True" >> $HOME/.cerbero/cerbero.cbc && \
    echo "local_sources=\"/cerbero/cerbero-sources\"" >> $HOME/.cerbero/cerbero.cbc && \
    cd cerbero && \
      ./cerbero-uninstalled bootstrap -y --system-only && \
      ./cerbero-uninstalled fetch-bootstrap --build-tools-only && \
      ./cerbero-uninstalled fetch-package gstreamer-1.0 && \
      cd .. && \
    dnf clean all
