#!/bin/sh

LANG=C
LC_COLLATE=C
export LANG
export LC_COLLATE

Template=$1;
srcfile=$2;

if test x"$1" = x ; then
	echo "$0 Objectname [srcfile]\n";
	echo "  creates gstobjectname.{c,h} implementing GstObjectname,\n";
	echo "  subclassing GstAudiofilter.\n";
	exit 1;
fi

if test x"$2" = x ; then
	srcfile="gstaudiofiltertemplate.c"
fi

id=`echo '$Id$' | sed \
	-e 's/\$I[d]: \([^$]*\)\$/\1/g'`
echo $id

TEMPLATE=`echo $Template | tr [:lower:] [:upper:]`
template=`echo $Template | tr [:upper:] [:lower:]`

echo TEMPLATE $TEMPLATE
echo template $template

# remember to break up the Id: in the line below
sed \
	-e 's/gstaudiofiltertemplate\.c/SOURCEFILE/g' \
	-e "s/AudiofilterTemplate/$Template/g" \
	-e "s/audiofiltertemplate/$template/g" \
	-e "s/VIDEOFILTERTEMPLATE/$TEMPLATE/g" \
	-e 's/\$I[d]: \([^$]*\)\$/\1/g' \
	-e 's/SOURCEFILE/gstaudiofiltertemplate\.c/g' \
	-e "s%MAKEFILTERVERSION%$id%g" \
	$srcfile >gst$template.c.tmp && mv gst$template.c.tmp gst$template.c

