/*
 * GStreamer
 * Copyright (C) 2025 Collabora Ltd.
 *  Authors: Daniel Morin <daniel.morin@collabora.com>
 *           Vineet Suryan <vineet.suryan@collabora.com>
 *           Santosh Mahto <santosh.mahto@collabora.com>
 *           Olivier Crête <olivier.crete@collabora.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

/**
 * SECTION:element-yoloobbv8tensordec
 * @short_description: Decode tensors from a YOLOv8 oriented bounding box
 * models
 *
 * This element can parse per-buffer inference tensors meta data generated by an upstream
 * inference element
 *
 * ## Example launch command:
 *
 * Test image file, model file and labels file can be found here :
 * https://gitlab.collabora.com/gstreamer/onnx-models
 *
 * gst-launch-1.0 v4l2src ! videorate max-rate=3 ! videoconvertscale \
 *  ! onnxinference  model-file=yolov8n-obb.onnx \
 *  ! yoloobbv8tensordec class-confidence-threshold=0.8 iou-threshold=0.3 \
 *    max-detections=100 label-file=labels/DOTAv1.txt \
 *  ! objectdetectionoverlay \
 *  ! glimagesink sink="gtkglsink processing-deadline=300000000"
 *
 * The original repository of the Yolo is located at
 * https://github.com/ultralytics/ultralytics.
 *
 * Since: 1.30
 */

#ifdef HAVE_CONFI_H
#include "config.h"
#endif

#include "gstyoloobbtensordecoder.h"

#include <gst/analytics/analytics.h>
#include <gio/gio.h>

#include <math.h>

#define YOLO_OBB "yolo-v8-obb-out"
GQuark YOLO_OBB_ID;

/* *INDENT-OFF* */
static GstStaticPadTemplate gst_yolo_obb_tensor_decoder_sink_template =
GST_STATIC_PAD_TEMPLATE ("sink",
    GST_PAD_SINK,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS ("video/x-raw,"
        "tensors=(structure)["
          "tensorgroups,"
            "yolo-v8-obb-out=(/uniquelist){"
            "(GstCaps)["
              "tensor/strided,"
                "tensor-id=yolo-v8-obb-out,"
                "dims=(int)<1, [1, max], [1,max]>,"
                "dims-order=(string)col-major,"
                "type=(string)float32"
              "]"
            "}"
        "]"
      ));
/* *INDENT-ON* */


GST_DEBUG_CATEGORY_STATIC (yolo_obb_tensor_decoder_debug);
#define GST_CAT_DEFAULT yolo_obb_tensor_decoder_debug

GST_ELEMENT_REGISTER_DEFINE (yolo_obb_tensor_decoder, "yoloobbv8tensordec",
    GST_RANK_SECONDARY, GST_TYPE_YOLO_OBB_TENSOR_DECODER);

/* GstYoloObbTensorDecoder Prototypes */
static GstFlowReturn gst_yolo_obb_tensor_decoder_transform_ip (GstBaseTransform
    * trans, GstBuffer * buf);

static gfloat gst_yolo_obb_tensor_decoder_iou (GstYoloTensorDecoder * self,
    BBox * bb1, BBox * bb2);
static void gst_yolo_obb_tensor_decoder_object_found (GstYoloTensorDecoder * od,
    GstAnalyticsRelationMeta * rmeta, BBox * bb, gfloat confidence,
    GQuark class_quark, const gfloat * candidate_masks, gsize offset,
    guint count);

G_DEFINE_TYPE (GstYoloObbTensorDecoder, gst_yolo_obb_tensor_decoder,
    GST_TYPE_YOLO_TENSOR_DECODER);


static void
gst_yolo_obb_tensor_decoder_class_init (GstYoloObbTensorDecoderClass * klass)
{
  GstElementClass *element_class = (GstElementClass *) klass;
  GstBaseTransformClass *basetransform_class = (GstBaseTransformClass *) klass;
  GstYoloTensorDecoderClass *od_class = (GstYoloTensorDecoderClass *) klass;

  /* Define GstYoloObbTensorDecoder debug category. */
  GST_DEBUG_CATEGORY_INIT (yolo_obb_tensor_decoder_debug,
      "yoloobbv8tensordec", 0,
      "Tensor decoder for Yolo Oriented Bounding Boxes (OBB) models");

  YOLO_OBB_ID = g_quark_from_static_string (YOLO_OBB);

  gst_element_class_set_static_metadata (element_class,
      "YOLO v8-11 oriented bounding box tensor decoder", "Tensordecoder/Video",
      "Decode tensors output from the inference of Yolo model (obb)"
      " on video frames. It works with YOLO version 8-11 models.",
      "Daniel Morin <daniel.morin@collabora.com>, Santosh Mahto <santosh.mahto@collabora.com>");

  gst_element_class_add_pad_template (element_class,
      gst_static_pad_template_get (&gst_yolo_obb_tensor_decoder_sink_template));

  basetransform_class->transform_ip = gst_yolo_obb_tensor_decoder_transform_ip;

  od_class->object_found = gst_yolo_obb_tensor_decoder_object_found;
  od_class->iou = gst_yolo_obb_tensor_decoder_iou;

  /* Workaround hotdoc bug */
  gst_type_mark_as_plugin_api (GST_TYPE_YOLO_TENSOR_DECODER, 0);
}

static void
gst_yolo_obb_tensor_decoder_init (GstYoloObbTensorDecoder * self)
{
}

static gboolean
gst_yolo_obb_tensor_decoder_get_tensors (GstYoloObbTensorDecoder * self,
    GstBuffer * buf, const GstTensor ** detections_tensor)
{
  GstMeta *meta = NULL;
  gpointer iter_state = NULL;

  if (!gst_buffer_get_meta (buf, GST_TENSOR_META_API_TYPE)) {
    GST_WARNING_OBJECT (self,
        "missing tensor meta from buffer %" GST_PTR_FORMAT, buf);
    return FALSE;
  }

  while ((meta = gst_buffer_iterate_meta_filtered (buf, &iter_state,
              GST_TENSOR_META_API_TYPE))) {
    GstTensorMeta *tmeta = (GstTensorMeta *) meta;
    const gsize YOLO_OBB_TENSOR_N_DIMS = 3;
    static const gsize detections_dims[3] = { 1, G_MAXSIZE, G_MAXSIZE };

    *detections_tensor = gst_tensor_meta_get_typed_tensor (tmeta,
        YOLO_OBB_ID, GST_TENSOR_DATA_TYPE_FLOAT32,
        GST_TENSOR_DIM_ORDER_COL_MAJOR, YOLO_OBB_TENSOR_N_DIMS,
        detections_dims);

    if (*detections_tensor == NULL)
      continue;

    if ((*detections_tensor)->dims[1] < 4 + 1 + 1) {
      GST_WARNING_OBJECT (self, "Ignore tensor because dims[1] is %zu < %d",
          (*detections_tensor)->dims[1], 4 + 1 + 1);
      continue;
    }

    return TRUE;
  }

  return FALSE;
}

/* gst_yolo_obb_tensor_decoder_transform_ip:
 * @trans: Instance
 * @buf:inout: Buffer containing media and where tensors can be attached
 * @return: Flow errors
 * Decode Yolo tensors, post-process tensors and store decoded information
 * into an analytics-meta that is attached to the buffer before been pushed
 * downstream.
 */
static GstFlowReturn
gst_yolo_obb_tensor_decoder_transform_ip (GstBaseTransform * trans,
    GstBuffer * buf)
{
  GstYoloObbTensorDecoder *self = GST_YOLO_OBB_TENSOR_DECODER (trans);
  GstYoloTensorDecoder *od = GST_YOLO_TENSOR_DECODER (trans);
  GstAnalyticsRelationMeta *rmeta;
  const GstTensor *detections_tensor;

  if (!gst_yolo_obb_tensor_decoder_get_tensors (self, buf, &detections_tensor)) {
    GST_WARNING_OBJECT (self, "Couldn't find detections tensor, skipping");
    return GST_FLOW_OK;
  }

  rmeta = gst_buffer_add_analytics_relation_meta (buf);
  if (rmeta == NULL) {
    GST_ELEMENT_ERROR (trans, STREAM, FAILED, (NULL),
        ("Analytics Relation meta allocation failed"));
    return GST_FLOW_ERROR;
  }

  if (!gst_yolo_tensor_decoder_decode_f32 (od, rmeta, detections_tensor, 1))
    return GST_FLOW_ERROR;

  return GST_FLOW_OK;;
}

typedef struct
{
  gfloat x, y;
} Point;

static void
get_rotated_corners (const BBox * box, Point * corners)
{
  gfloat cx = box->x;
  gfloat cy = box->y;
  gfloat w = box->w;
  gfloat h = box->h;
  gfloat r = box->r;

  gfloat cos_r = cos (r);
  gfloat sin_r = sin (r);

  gfloat dx_w = w * 0.5f;
  gfloat dy_h = h * 0.5f;

  /* Corners relative to center (before rotation)
     BL: (-w/2, +h/2) -> this depends on coordinate system.
     Usually Y is down in images.
     TL: (-w/2, -h/2)
     TR: (+w/2, -h/2)
     BR: (+w/2, +h/2)
     BL: (-w/2, +h/2)
   */

  /* We'll just generate 4 corners in order. Order matters for
     Shoelace/clipping. Let's do: Top-Left, Top-Right, Bottom-Right, Bottom-Left
   */
  static const gfloat signs[4][2] = {
    {-1, -1},                   /* Top Left */
    {1, -1},                    /* Top Right */
    {1, 1},                     /* Bottom Left */
    {-1, 1}                     /* Bottom Right */
  };

  for (int i = 0; i < 4; i++) {
    gfloat dx = signs[i][0] * dx_w;
    gfloat dy = signs[i][1] * dy_h;

    /* Rotate and translate */
    corners[i].x = cx + (dx * cos_r - dy * sin_r);
    corners[i].y = cy + (dx * sin_r + dy * cos_r);
  }
}

static gfloat
get_polygon_area (const Point * points, int n)
{
  gfloat area = 0.0f;

  for (int i = 0; i < n; i++) {
    int j = (i + 1) % n;

    area += points[i].x * points[j].y;
    area -= points[j].x * points[i].y;
  }

  return 0.5f * fabsf (area);
}

/* Helpers for Sutherland-Hodgman */

/* Check if point P is inside the edge defined by A->B.
   "Inside" means to the left of vector AB (assuming CCW winding)
   or just consistent side.
   Cross product (B-A) x (P-A) > 0 for CCW.
 */
static gboolean
is_inside (Point p, Point a, Point b)
{
  return (b.x - a.x) * (p.y - a.y) - (b.y - a.y) * (p.x - a.x) >= 0;
}

static void
get_intersection_point (Point cp1, Point cp2, Point s, Point e, Point * res)
{
  Point ip = { 0, 0 };
  gfloat dcx = cp1.x - cp2.x;
  gfloat dcy = cp1.y - cp2.y;
  gfloat dsx = s.x - e.x;
  gfloat dsy = s.y - e.y;
  gfloat det = dcx * dsy - dcy * dsx;

  if (fabsf (det) < 1e-6f) {
    *res = ip;                  /* Parallel lines, shouldn't happen if they intersect */
    return;
  }

  gfloat a = cp1.x * cp2.y - cp1.y * cp2.x;
  gfloat b = s.x * e.y - s.y * e.x;

  ip.x = (a * dsx - dcx * b) / det;
  ip.y = (a * dsy - dcy * b) / det;
  *res = ip;
}

static int
clip_polygon (const Point * subject, int subject_len, Point * output,
    Point clip_start, Point clip_end)
{
  int output_len = 0;
  if (subject_len == 0)
    return 0;

  Point prev = subject[subject_len - 1];

  for (int i = 0; i < subject_len; i++) {
    Point curr = subject[i];
    gboolean curr_in = is_inside (curr, clip_start, clip_end);
    gboolean prev_in = is_inside (prev, clip_start, clip_end);

    if (curr_in) {
      if (!prev_in) {
        get_intersection_point (prev, curr, clip_start, clip_end,
            &output[output_len++]);
      }
      output[output_len++] = curr;
    } else if (prev_in) {
      get_intersection_point (prev, curr, clip_start, clip_end,
          &output[output_len++]);
    }
    prev = curr;
  }
  return output_len;
}

static gfloat
gst_yolo_obb_tensor_decoder_iou (GstYoloTensorDecoder * self, BBox * bb1,
    BBox * bb2)
{

  Point poly1[4];
  Point poly2[4];
  Point inter_poly1[8];         /* Max vertices can increase during clipping */
  Point inter_poly2[8];

  get_rotated_corners (bb1, poly1);
  get_rotated_corners (bb2, poly2);

  gfloat area1 = bb1->w * bb1->h;
  gfloat area2 = bb2->w * bb2->h;

  /* Use poly1 as subject, poly2 as clipper (or vice versa, but we clip against
     each edge of poly2 iteratively) */

  /* Initialize intersection polygon with poly1 */
  Point *input_poly = poly1;
  int input_len = 4;

  /* Clip against each edge of poly2 */
  for (int i = 0; i < 4; i++) {
    Point clip_start = poly2[i];
    Point clip_end = poly2[(i + 1) % 4];
    int output_len;

    /* Toggle buffers */
    Point *next_buffer =
        (input_poly == inter_poly1) ? inter_poly2 : inter_poly1;

    output_len = clip_polygon (input_poly, input_len, next_buffer, clip_start,
        clip_end);

    input_poly = next_buffer;
    input_len = output_len;

    if (input_len == 0)
      break;
  }

  gfloat intersection_area = get_polygon_area (input_poly, input_len);
  gfloat union_area = area1 + area2 - intersection_area;

  if (union_area <= 0.0f)
    return 0.0f;

  return intersection_area / union_area;
}

static void
gst_yolo_obb_tensor_decoder_object_found (GstYoloTensorDecoder * od,
    GstAnalyticsRelationMeta * rmeta, BBox * bb, gfloat confidence,
    GQuark class_quark, const gfloat * candidate_masks, gsize offset,
    guint count)
{
  gst_analytics_relation_meta_add_oriented_od_mtd (rmeta, class_quark, bb->x,
      bb->y, bb->w, bb->h, bb->r, confidence, NULL);
}
