
/* autogenerated from gstvideoscaleorc.orc */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#ifndef DISABLE_ORC
#include <orc/orc.h>
#endif
#include <glib.h>

#ifndef _ORC_INTEGER_TYPEDEFS_
#define _ORC_INTEGER_TYPEDEFS_
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#include <stdint.h>
typedef int8_t orc_int8;
typedef int16_t orc_int16;
typedef int32_t orc_int32;
typedef int64_t orc_int64;
typedef uint8_t orc_uint8;
typedef uint16_t orc_uint16;
typedef uint32_t orc_uint32;
typedef uint64_t orc_uint64;
#elif defined(_MSC_VER)
typedef signed __int8 orc_int8;
typedef signed __int16 orc_int16;
typedef signed __int32 orc_int32;
typedef signed __int64 orc_int64;
typedef unsigned __int8 orc_uint8;
typedef unsigned __int16 orc_uint16;
typedef unsigned __int32 orc_uint32;
typedef unsigned __int64 orc_uint64;
#else
#include <limits.h>
typedef signed char orc_int8;
typedef short orc_int16;
typedef int orc_int32;
typedef unsigned char orc_uint8;
typedef unsigned short orc_uint16;
typedef unsigned int orc_uint32;
#if INT_MAX == LONG_MAX
typedef long long orc_int64;
typedef unsigned long long orc_uint64;
#else
typedef long orc_int64;
typedef unsigned long orc_uint64;
#endif
#endif
typedef union
{
  orc_int16 i;
  orc_int8 x2[2];
} orc_union16;
typedef union
{
  orc_int32 i;
  float f;
  orc_int16 x2[2];
  orc_int8 x4[4];
} orc_union32;
typedef union
{
  orc_int64 i;
  double f;
  orc_int32 x2[2];
  orc_int16 x4[4];
} orc_union64;
#endif

void orc_merge_linear_u8 (orc_uint8 * d1, const orc_uint8 * s1,
    const orc_uint8 * s2, int p1, int p2, int n);
void orc_merge_linear_u16 (orc_uint16 * d1, const orc_uint16 * s1,
    const orc_uint16 * s2, int p1, int p2, int n);
void orc_splat_u16 (orc_uint16 * d1, int p1, int n);
void orc_splat_u32 (orc_uint32 * d1, int p1, int n);

void gst_videoscale_orc_init (void);


/* begin Orc C target preamble */
#define ORC_CLAMP(x,a,b) ((x)<(a) ? (a) : ((x)>(b) ? (b) : (x)))
#define ORC_ABS(a) ((a)<0 ? -(a) : (a))
#define ORC_MIN(a,b) ((a)<(b) ? (a) : (b))
#define ORC_MAX(a,b) ((a)>(b) ? (a) : (b))
#define ORC_SB_MAX 127
#define ORC_SB_MIN (-1-ORC_SB_MAX)
#define ORC_UB_MAX 255
#define ORC_UB_MIN 0
#define ORC_SW_MAX 32767
#define ORC_SW_MIN (-1-ORC_SW_MAX)
#define ORC_UW_MAX 65535
#define ORC_UW_MIN 0
#define ORC_SL_MAX 2147483647
#define ORC_SL_MIN (-1-ORC_SL_MAX)
#define ORC_UL_MAX 4294967295U
#define ORC_UL_MIN 0
#define ORC_CLAMP_SB(x) ORC_CLAMP(x,ORC_SB_MIN,ORC_SB_MAX)
#define ORC_CLAMP_UB(x) ORC_CLAMP(x,ORC_UB_MIN,ORC_UB_MAX)
#define ORC_CLAMP_SW(x) ORC_CLAMP(x,ORC_SW_MIN,ORC_SW_MAX)
#define ORC_CLAMP_UW(x) ORC_CLAMP(x,ORC_UW_MIN,ORC_UW_MAX)
#define ORC_CLAMP_SL(x) ORC_CLAMP(x,ORC_SL_MIN,ORC_SL_MAX)
#define ORC_CLAMP_UL(x) ORC_CLAMP(x,ORC_UL_MIN,ORC_UL_MAX)
#define ORC_SWAP_W(x) ((((x)&0xff)<<8) | (((x)&0xff00)>>8))
#define ORC_SWAP_L(x) ((((x)&0xff)<<24) | (((x)&0xff00)<<8) | (((x)&0xff0000)>>8) | (((x)&0xff000000)>>24))
#define ORC_SWAP_Q(x) ((((x)&0xffULL)<<56) | (((x)&0xff00ULL)<<40) | (((x)&0xff0000ULL)<<24) | (((x)&0xff000000ULL)<<8) | (((x)&0xff00000000ULL)>>8) | (((x)&0xff0000000000ULL)>>24) | (((x)&0xff000000000000ULL)>>40) | (((x)&0xff00000000000000ULL)>>56))
#define ORC_PTR_OFFSET(ptr,offset) ((void *)(((unsigned char *)(ptr)) + (offset)))
#define ORC_DENORMAL(x) ((x) & ((((x)&0x7f800000) == 0) ? 0xff800000 : 0xffffffff))
#define ORC_ISNAN(x) ((((x)&0x7f800000) == 0x7f800000) && (((x)&0x007fffff) != 0))
#define ORC_DENORMAL_DOUBLE(x) ((x) & ((((x)&0x7ff0000000000000ULL) == 0) ? 0xfff0000000000000ULL : 0xffffffffffffffffULL))
#define ORC_ISNAN_DOUBLE(x) ((((x)&0x7ff0000000000000ULL) == 0x7ff0000000000000ULL) && (((x)&0x000fffffffffffffULL) != 0))
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define ORC_RESTRICT restrict
#elif defined(__GNUC__) && __GNUC__ >= 4
#define ORC_RESTRICT __restrict__
#else
#define ORC_RESTRICT
#endif
/* end Orc C target preamble */



/* orc_merge_linear_u8 */
#ifdef DISABLE_ORC
void
orc_merge_linear_u8 (orc_uint8 * d1, const orc_uint8 * s1, const orc_uint8 * s2,
    int p1, int p2, int n)
{
  int i;
  orc_int8 *ORC_RESTRICT ptr0;
  const orc_int8 *ORC_RESTRICT ptr4;
  const orc_int8 *ORC_RESTRICT ptr5;
  orc_int8 var34;
  orc_int8 var35;
  orc_int8 var36;
  orc_int8 var37;
  orc_union16 var38;
  orc_int8 var39;
  orc_union16 var40;
  orc_union16 var41;
  orc_union16 var42;
  orc_union16 var43;
  orc_union16 var44;

  ptr0 = (orc_int8 *) d1;
  ptr4 = (orc_int8 *) s1;
  ptr5 = (orc_int8 *) s2;

  /* 1: loadpb */
  var35 = p1;
  /* 4: loadpb */
  var37 = p2;
  /* 7: loadpw */
  var38.i = 0x00000080;         /* 128 or 6.32404e-322f */

  for (i = 0; i < n; i++) {
    /* 0: loadb */
    var34 = ptr4[i];
    /* 2: mulubw */
    var40.i = (orc_uint8) var34 *(orc_uint8) var35;
    /* 3: loadb */
    var36 = ptr5[i];
    /* 5: mulubw */
    var41.i = (orc_uint8) var36 *(orc_uint8) var37;
    /* 6: addw */
    var42.i = var40.i + var41.i;
    /* 8: addw */
    var43.i = var42.i + var38.i;
    /* 9: shruw */
    var44.i = ((orc_uint16) var43.i) >> 8;
    /* 10: convwb */
    var39 = var44.i;
    /* 11: storeb */
    ptr0[i] = var39;
  }

}

#else
static void
_backup_orc_merge_linear_u8 (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_int8 *ORC_RESTRICT ptr0;
  const orc_int8 *ORC_RESTRICT ptr4;
  const orc_int8 *ORC_RESTRICT ptr5;
  orc_int8 var34;
  orc_int8 var35;
  orc_int8 var36;
  orc_int8 var37;
  orc_union16 var38;
  orc_int8 var39;
  orc_union16 var40;
  orc_union16 var41;
  orc_union16 var42;
  orc_union16 var43;
  orc_union16 var44;

  ptr0 = (orc_int8 *) ex->arrays[0];
  ptr4 = (orc_int8 *) ex->arrays[4];
  ptr5 = (orc_int8 *) ex->arrays[5];

  /* 1: loadpb */
  var35 = ex->params[24];
  /* 4: loadpb */
  var37 = ex->params[25];
  /* 7: loadpw */
  var38.i = 0x00000080;         /* 128 or 6.32404e-322f */

  for (i = 0; i < n; i++) {
    /* 0: loadb */
    var34 = ptr4[i];
    /* 2: mulubw */
    var40.i = (orc_uint8) var34 *(orc_uint8) var35;
    /* 3: loadb */
    var36 = ptr5[i];
    /* 5: mulubw */
    var41.i = (orc_uint8) var36 *(orc_uint8) var37;
    /* 6: addw */
    var42.i = var40.i + var41.i;
    /* 8: addw */
    var43.i = var42.i + var38.i;
    /* 9: shruw */
    var44.i = ((orc_uint16) var43.i) >> 8;
    /* 10: convwb */
    var39 = var44.i;
    /* 11: storeb */
    ptr0[i] = var39;
  }

}

static OrcProgram *_orc_program_orc_merge_linear_u8;
void
orc_merge_linear_u8 (orc_uint8 * d1, const orc_uint8 * s1, const orc_uint8 * s2,
    int p1, int p2, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  OrcProgram *p = _orc_program_orc_merge_linear_u8;
  void (*func) (OrcExecutor *);

  ex->program = p;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *) s1;
  ex->arrays[ORC_VAR_S2] = (void *) s2;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  func = p->code_exec;
  func (ex);
}
#endif


/* orc_merge_linear_u16 */
#ifdef DISABLE_ORC
void
orc_merge_linear_u16 (orc_uint16 * d1, const orc_uint16 * s1,
    const orc_uint16 * s2, int p1, int p2, int n)
{
  int i;
  orc_union16 *ORC_RESTRICT ptr0;
  const orc_union16 *ORC_RESTRICT ptr4;
  const orc_union16 *ORC_RESTRICT ptr5;
  orc_union16 var34;
  orc_union16 var35;
  orc_union16 var36;
  orc_union16 var37;
  orc_union16 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;
  orc_union32 var42;

  ptr0 = (orc_union16 *) d1;
  ptr4 = (orc_union16 *) s1;
  ptr5 = (orc_union16 *) s2;

  /* 1: loadpw */
  var35.i = p1;
  /* 4: loadpw */
  var37.i = p2;

  for (i = 0; i < n; i++) {
    /* 0: loadw */
    var34 = ptr4[i];
    /* 2: muluwl */
    var39.i = (orc_uint16) var34.i * (orc_uint16) var35.i;
    /* 3: loadw */
    var36 = ptr5[i];
    /* 5: muluwl */
    var40.i = (orc_uint16) var36.i * (orc_uint16) var37.i;
    /* 6: addl */
    var41.i = var39.i + var40.i;
    /* 7: shrul */
    var42.i = ((orc_uint32) var41.i) >> 16;
    /* 8: convlw */
    var38.i = var42.i;
    /* 9: storew */
    ptr0[i] = var38;
  }

}

#else
static void
_backup_orc_merge_linear_u16 (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union16 *ORC_RESTRICT ptr0;
  const orc_union16 *ORC_RESTRICT ptr4;
  const orc_union16 *ORC_RESTRICT ptr5;
  orc_union16 var34;
  orc_union16 var35;
  orc_union16 var36;
  orc_union16 var37;
  orc_union16 var38;
  orc_union32 var39;
  orc_union32 var40;
  orc_union32 var41;
  orc_union32 var42;

  ptr0 = (orc_union16 *) ex->arrays[0];
  ptr4 = (orc_union16 *) ex->arrays[4];
  ptr5 = (orc_union16 *) ex->arrays[5];

  /* 1: loadpw */
  var35.i = ex->params[24];
  /* 4: loadpw */
  var37.i = ex->params[25];

  for (i = 0; i < n; i++) {
    /* 0: loadw */
    var34 = ptr4[i];
    /* 2: muluwl */
    var39.i = (orc_uint16) var34.i * (orc_uint16) var35.i;
    /* 3: loadw */
    var36 = ptr5[i];
    /* 5: muluwl */
    var40.i = (orc_uint16) var36.i * (orc_uint16) var37.i;
    /* 6: addl */
    var41.i = var39.i + var40.i;
    /* 7: shrul */
    var42.i = ((orc_uint32) var41.i) >> 16;
    /* 8: convlw */
    var38.i = var42.i;
    /* 9: storew */
    ptr0[i] = var38;
  }

}

static OrcProgram *_orc_program_orc_merge_linear_u16;
void
orc_merge_linear_u16 (orc_uint16 * d1, const orc_uint16 * s1,
    const orc_uint16 * s2, int p1, int p2, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  OrcProgram *p = _orc_program_orc_merge_linear_u16;
  void (*func) (OrcExecutor *);

  ex->program = p;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->arrays[ORC_VAR_S1] = (void *) s1;
  ex->arrays[ORC_VAR_S2] = (void *) s2;
  ex->params[ORC_VAR_P1] = p1;
  ex->params[ORC_VAR_P2] = p2;

  func = p->code_exec;
  func (ex);
}
#endif


/* orc_splat_u16 */
#ifdef DISABLE_ORC
void
orc_splat_u16 (orc_uint16 * d1, int p1, int n)
{
  int i;
  orc_union16 *ORC_RESTRICT ptr0;
  orc_union16 var32;
  orc_union16 var33;

  ptr0 = (orc_union16 *) d1;

  /* 0: loadpw */
  var32.i = p1;

  for (i = 0; i < n; i++) {
    /* 1: copyw */
    var33.i = var32.i;
    /* 2: storew */
    ptr0[i] = var33;
  }

}

#else
static void
_backup_orc_splat_u16 (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union16 *ORC_RESTRICT ptr0;
  orc_union16 var32;
  orc_union16 var33;

  ptr0 = (orc_union16 *) ex->arrays[0];

  /* 0: loadpw */
  var32.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 1: copyw */
    var33.i = var32.i;
    /* 2: storew */
    ptr0[i] = var33;
  }

}

static OrcProgram *_orc_program_orc_splat_u16;
void
orc_splat_u16 (orc_uint16 * d1, int p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  OrcProgram *p = _orc_program_orc_splat_u16;
  void (*func) (OrcExecutor *);

  ex->program = p;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  func = p->code_exec;
  func (ex);
}
#endif


/* orc_splat_u32 */
#ifdef DISABLE_ORC
void
orc_splat_u32 (orc_uint32 * d1, int p1, int n)
{
  int i;
  orc_union32 *ORC_RESTRICT ptr0;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *) d1;

  /* 0: loadpl */
  var32.i = p1;

  for (i = 0; i < n; i++) {
    /* 1: copyl */
    var33.i = var32.i;
    /* 2: storel */
    ptr0[i] = var33;
  }

}

#else
static void
_backup_orc_splat_u32 (OrcExecutor * ORC_RESTRICT ex)
{
  int i;
  int n = ex->n;
  orc_union32 *ORC_RESTRICT ptr0;
  orc_union32 var32;
  orc_union32 var33;

  ptr0 = (orc_union32 *) ex->arrays[0];

  /* 0: loadpl */
  var32.i = ex->params[24];

  for (i = 0; i < n; i++) {
    /* 1: copyl */
    var33.i = var32.i;
    /* 2: storel */
    ptr0[i] = var33;
  }

}

static OrcProgram *_orc_program_orc_splat_u32;
void
orc_splat_u32 (orc_uint32 * d1, int p1, int n)
{
  OrcExecutor _ex, *ex = &_ex;
  OrcProgram *p = _orc_program_orc_splat_u32;
  void (*func) (OrcExecutor *);

  ex->program = p;

  ex->n = n;
  ex->arrays[ORC_VAR_D1] = d1;
  ex->params[ORC_VAR_P1] = p1;

  func = p->code_exec;
  func (ex);
}
#endif


void
gst_videoscale_orc_init (void)
{
#ifndef DISABLE_ORC
  {
    /* orc_merge_linear_u8 */
    OrcProgram *p;
    OrcCompileResult result;

    p = orc_program_new ();
    orc_program_set_name (p, "orc_merge_linear_u8");
    orc_program_set_backup_function (p, _backup_orc_merge_linear_u8);
    orc_program_add_destination (p, 1, "d1");
    orc_program_add_source (p, 1, "s1");
    orc_program_add_source (p, 1, "s2");
    orc_program_add_constant (p, 4, 0x00000080, "c1");
    orc_program_add_constant (p, 4, 0x00000008, "c2");
    orc_program_add_constant (p, 0, 0x00000000, "c3");
    orc_program_add_constant (p, 0, 0x00000000, "c4");
    orc_program_add_constant (p, 0, 0x00000000, "c5");
    orc_program_add_constant (p, 0, 0x00000000, "c6");
    orc_program_add_constant (p, 0, 0x00000000, "c7");
    orc_program_add_constant (p, 0, 0x00000000, "c8");
    orc_program_add_parameter (p, 1, "p1");
    orc_program_add_parameter (p, 1, "p2");
    orc_program_add_temporary (p, 2, "t1");
    orc_program_add_temporary (p, 2, "t2");

    orc_program_append_2 (p, "mulubw", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_P1,
        ORC_VAR_D1);
    orc_program_append_2 (p, "mulubw", 0, ORC_VAR_T2, ORC_VAR_S2, ORC_VAR_P2,
        ORC_VAR_D1);
    orc_program_append_2 (p, "addw", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T2,
        ORC_VAR_D1);
    orc_program_append_2 (p, "addw", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1,
        ORC_VAR_D1);
    orc_program_append_2 (p, "shruw", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C2,
        ORC_VAR_D1);
    orc_program_append_2 (p, "convwb", 0, ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1,
        ORC_VAR_D1);

    result = orc_program_compile (p);

    _orc_program_orc_merge_linear_u8 = p;
  }
  {
    /* orc_merge_linear_u16 */
    OrcProgram *p;
    OrcCompileResult result;

    p = orc_program_new ();
    orc_program_set_name (p, "orc_merge_linear_u16");
    orc_program_set_backup_function (p, _backup_orc_merge_linear_u16);
    orc_program_add_destination (p, 2, "d1");
    orc_program_add_source (p, 2, "s1");
    orc_program_add_source (p, 2, "s2");
    orc_program_add_constant (p, 4, 0x00000010, "c1");
    orc_program_add_constant (p, 0, 0x00000000, "c2");
    orc_program_add_constant (p, 0, 0x00000000, "c3");
    orc_program_add_constant (p, 0, 0x00000000, "c4");
    orc_program_add_constant (p, 0, 0x00000000, "c5");
    orc_program_add_constant (p, 0, 0x00000000, "c6");
    orc_program_add_constant (p, 0, 0x00000000, "c7");
    orc_program_add_constant (p, 0, 0x00000000, "c8");
    orc_program_add_parameter (p, 2, "p1");
    orc_program_add_parameter (p, 2, "p2");
    orc_program_add_temporary (p, 4, "t1");
    orc_program_add_temporary (p, 4, "t2");

    orc_program_append_2 (p, "muluwl", 0, ORC_VAR_T1, ORC_VAR_S1, ORC_VAR_P1,
        ORC_VAR_D1);
    orc_program_append_2 (p, "muluwl", 0, ORC_VAR_T2, ORC_VAR_S2, ORC_VAR_P2,
        ORC_VAR_D1);
    orc_program_append_2 (p, "addl", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_T2,
        ORC_VAR_D1);
    orc_program_append_2 (p, "shrul", 0, ORC_VAR_T1, ORC_VAR_T1, ORC_VAR_C1,
        ORC_VAR_D1);
    orc_program_append_2 (p, "convlw", 0, ORC_VAR_D1, ORC_VAR_T1, ORC_VAR_D1,
        ORC_VAR_D1);

    result = orc_program_compile (p);

    _orc_program_orc_merge_linear_u16 = p;
  }
  {
    /* orc_splat_u16 */
    OrcProgram *p;
    OrcCompileResult result;

    p = orc_program_new ();
    orc_program_set_name (p, "orc_splat_u16");
    orc_program_set_backup_function (p, _backup_orc_splat_u16);
    orc_program_add_destination (p, 2, "d1");
    orc_program_add_constant (p, 0, 0x00000000, "c1");
    orc_program_add_constant (p, 0, 0x00000000, "c2");
    orc_program_add_constant (p, 0, 0x00000000, "c3");
    orc_program_add_constant (p, 0, 0x00000000, "c4");
    orc_program_add_constant (p, 0, 0x00000000, "c5");
    orc_program_add_constant (p, 0, 0x00000000, "c6");
    orc_program_add_constant (p, 0, 0x00000000, "c7");
    orc_program_add_constant (p, 0, 0x00000000, "c8");
    orc_program_add_parameter (p, 2, "p1");

    orc_program_append_2 (p, "copyw", 0, ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_D1,
        ORC_VAR_D1);

    result = orc_program_compile (p);

    _orc_program_orc_splat_u16 = p;
  }
  {
    /* orc_splat_u32 */
    OrcProgram *p;
    OrcCompileResult result;

    p = orc_program_new ();
    orc_program_set_name (p, "orc_splat_u32");
    orc_program_set_backup_function (p, _backup_orc_splat_u32);
    orc_program_add_destination (p, 4, "d1");
    orc_program_add_constant (p, 0, 0x00000000, "c1");
    orc_program_add_constant (p, 0, 0x00000000, "c2");
    orc_program_add_constant (p, 0, 0x00000000, "c3");
    orc_program_add_constant (p, 0, 0x00000000, "c4");
    orc_program_add_constant (p, 0, 0x00000000, "c5");
    orc_program_add_constant (p, 0, 0x00000000, "c6");
    orc_program_add_constant (p, 0, 0x00000000, "c7");
    orc_program_add_constant (p, 0, 0x00000000, "c8");
    orc_program_add_parameter (p, 4, "p1");

    orc_program_append_2 (p, "copyl", 0, ORC_VAR_D1, ORC_VAR_P1, ORC_VAR_D1,
        ORC_VAR_D1);

    result = orc_program_compile (p);

    _orc_program_orc_splat_u32 = p;
  }
#endif
}
