.TH "GStreamer" "1" "February 2002" "" ""
.SH "NAME"
gst\-launch\-ext \- Run a predefined GStreamer pipeline
.SH "SYNOPSIS"
\fBgst\-launch\-ext\fR \fIfilename [filename...]\fR
.SH "DESCRIPTION"
.LP 
\fIgst\-launch\-ext\fP is a tool that is used to run a basic predefined \fIGStreamer\fP pipeline.

All supported formats in GStreamer should be playable by simply typing:

 gst\-launch\-ext filename


.SH "SEE ALSO"
.BR gst\-guilaunch (1),
.BR gst\-complete (1),
.BR gst\-register (1),
.BR gst\-inspect (1),
.BR gst\-launch (1),
.SH "AUTHOR"
The GStreamer team at http://gstreamer.net/
