.TH "GStreamer" "1" "August 2013" "" ""
.SH "NAME"
gst\-play\-1.0 \- Simple command line playback testing tool
.SH "SYNOPSIS"
\fBgst\-play\-1.0\fR \fIFILE|DIRECTORY|URI [FILE2|DIRECTORY2|URI2]\fR
.SH "DESCRIPTION"
.LP
\fIgst\-play\-1.0\fP is a command line tool that can be used to test
basic playback using the playbin element. You can pass it individual files,
URIs or whole directories (in which case it will recurse into sub-directories
as well).

.SH "OPTIONS"
.l
\fIgst\-play\-1.0\fP accepts the following options:
.TP 8
.B  \-\-help
Print help synopsis and available command line options
.TP 8
.B  \-\-version
Print version and exit
.TP 8
.B  \-\-audiosink=SOMESINK
Use SOMESINK as audio sink instead of autoaudiosink.
.TP 8
.B  \-\-videosink=SOMESINK
Use SOMESINK as video sink instead of autovideosink.
.TP 8

.SH "SEE ALSO"
.BR gst\-inspect\-1.0 (1),
.BR gst\-launch\-1.0 (1),
.SH "AUTHOR"
The GStreamer team at http://gstreamer.freedesktop.org/
