.TH GStreamer 1 "June 2001"
.SH NAME
gstreamer\-complete - do bash completion for gstreamer\-launch command\-lines
.SH SYNOPSIS
.B  complete -C gstreamer\-complete gstreamer\-launch
.SH DESCRIPTION
.PP
\fIgstreamer\-complete\fP is a utility enabling bash to provide
context sensitive tab completion for \fIgstreamer\-launch\fP command\-lines.
.
See other docs for the syntax of \fIgstreamer\-launch\fP command\-lines.
.
You must have a version of bash which supports Programmable Completion.
Versions of bash which support this provide the \fIcomplete\fP builtin
command.
.
.SH USAGE
Generate the registry of available plugins by running
\fIgstreamer\-compprep\fP.
.
In your .bash_profile or other appropriate place, run
.TP 8
.B  complete -C gstreamer\-complete gstreamer\-launch
.SH SEE ALSO
.BR gstreamer\-compreg (1),
.BR gstreamer\-lanuch (1),
.BR gstreamer\-register (1),
.BR gstreamer\-inspect (1),
.BR gstreamer\-config (1)
.SH AUTHOR
The GStreamer team at http://gstreamer.net/
