
/* autogenerated from gstcogorc.orc */

#ifndef _GSTCOGORC_H_
#define _GSTCOGORC_H_

#include <glib.h>

#ifdef __cplusplus
extern "C" {
#endif

void cogorc_downsample_horiz_cosite_1tap (uint8_t * d1, const uint16_t * s1, int n);
void cogorc_downsample_horiz_cosite_3tap (uint8_t * d1, const uint16_t * s1, const uint16_t * s2, int n);
void cogorc_downsample_420_jpeg (uint8_t * d1, const uint16_t * s1, const uint16_t * s2, int n);
void cogorc_downsample_vert_halfsite_2tap (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int n);
void cogorc_downsample_vert_cosite_3tap (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int n);
void cogorc_downsample_vert_halfsite_4tap (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, const uint8_t * s4, int n);
void cogorc_upsample_horiz_cosite_1tap (uint8_t * d1, const uint8_t * s1, int n);
void cogorc_upsample_horiz_cosite (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int n);
void cogorc_upsample_vert_avgub (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int n);
void orc_unpack_yuyv_y (uint8_t * d1, const uint16_t * s1, int n);
void orc_unpack_yuyv_u (uint8_t * d1, const uint32_t * s1, int n);
void orc_unpack_yuyv_v (uint8_t * d1, const uint32_t * s1, int n);
void orc_pack_yuyv (uint32_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int n);
void orc_unpack_uyvy_y (uint8_t * d1, const uint16_t * s1, int n);
void orc_unpack_uyvy_u (uint8_t * d1, const uint32_t * s1, int n);
void orc_unpack_uyvy_v (uint8_t * d1, const uint32_t * s1, int n);
void orc_pack_uyvy (uint32_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int n);
void orc_addc_convert_u8_s16 (uint8_t * d1, const int16_t * s1, int n);
void orc_subc_convert_s16_u8 (int16_t * d1, const uint8_t * s1, int n);
void orc_splat_u8_ns (uint8_t * d1, int p1, int n);
void orc_splat_s16_ns (int16_t * d1, int p1, int n);
void orc_matrix2_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int p1, int p2, int p3, int n);
void orc_matrix2_11_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int p1, int p2, int n);
void orc_matrix2_12_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int p1, int p2, int n);
void orc_matrix3_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int p1, int p2, int p3, int p4, int n);
void orc_matrix3_100_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int p1, int p2, int p3, int n);
void orc_matrix3_100_offset_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int p1, int p2, int p3, int p4, int p5, int n);
void orc_matrix3_000_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int p1, int p2, int p3, int p4, int p5, int n);
void orc_pack_123x (uint32_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int p1, int n);
void orc_pack_x123 (uint32_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, int p1, int n);
void cogorc_combine2_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, int p1, int p2, int n);
void cogorc_combine4_u8 (uint8_t * d1, const uint8_t * s1, const uint8_t * s2, const uint8_t * s3, const uint8_t * s4, int p1, int p2, int p3, int p4, int n);
void cogorc_unpack_axyz_0 (uint8_t * d1, const uint32_t * s1, int n);
void cogorc_unpack_axyz_1 (uint8_t * d1, const uint32_t * s1, int n);
void cogorc_unpack_axyz_2 (uint8_t * d1, const uint32_t * s1, int n);
void cogorc_unpack_axyz_3 (uint8_t * d1, const uint32_t * s1, int n);

#ifdef __cplusplus
}
#endif

#endif

