[package]
name = "webrtc-app"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
edition = "2021"

[dependencies]
futures = "0.3"
async-std = "1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rand = { version = "0.9", features = ["thread_rng"] }
async-tungstenite = { version = "0.29", features = ["async-std-runtime", "async-native-tls"] }
gst = { package = "gstreamer", version = "0.23" }
gst-rtp = { package = "gstreamer-rtp", version = "0.23", features = ["v1_20"] }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.23" }
gst-sdp = { package = "gstreamer-sdp", version = "0.23" }
serde = "1"
serde_derive = "1"
serde_json = "1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
