name: Trigger Jenkins
on:
  push:
    tags:
      - 'v*.*'

jobs:
  Jenkins_Job:
    name: Build develop Branch
    runs-on: self-hosted
    steps:
      - name: Step 1 - Post to jenkins
        run: curl.exe -X POST "http://build:11ae983652068d3bdd54dfb6a552a193eb@192.168.1.156:8080/job/GStreamer_1.22/build"
